[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "md-khalid05", email = "mdkhalidansari04@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "numpy>=2.5.2",
    "pandas<3.0.0",
    "pyarrow>=25.0.1",
    "pyspark>=4.2.0",
]

[project.scripts]
dev = "dev:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
